### ISSUE TITLE
2019_12_27_154630_create_product_models_table 

### ISSUE THREAD

**Issue by djbiswas** [softx101/production-and-sales-management-application#1]
Here it's looking that we make relation but we did not create the table row.

Update:
Schema::create('product_models', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->unsignedBigInteger('product_category_id');
            $table->string('product_model_name');
            $table->string('model_description')->nullable();
            $table->unsignedBigInteger('product_type_id');
            $table->foreign('product_type_id')->references('id')
                ->on('product_types')->onUpdate('cascade')->onDelete('cascade');
            $table->timestamps();
        });
--------------------------------------------
Past: 
Schema::create('product_models', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->unsignedBigInteger('product_category_id');
            $table->string('product_model_name');
            $table->string('model_description')->nullable();
            $table->foreign('product_type_id')->references('id')
                ->on('product_types')->onUpdate('cascade')->onDelete('cascade');
            $table->timestamps();
        });

**Comment by softx101** [comment]
$table->unsignedBigInteger('product_type_id'); -- issue has been solved.
